---
title: "Boston Marathon"
output: github_document
---

```{r}
library(tidyverse)
library(viridis)
library(ggridges)
library(patchwork)
```


```{r}
years_1 <- c(1900:2012, 2014)
years_2 <- c(2015:2019)

importing_data = function(x){
 
  if(str_detect(x, str_c(years_1, collapse = "|"))) {
  read_csv(x, na = c("NULL", "", "0"), col_types = "cicccciiiicc") 
  } 
  
  else if(str_detect(x, str_c(years_2, collapse = "|"))){
    read_csv(x, na = c("NULL", "", "0"), col_types = "cccicccccccccccccccccciiiiccc")
  }
}

boston_df <- 
  tibble(list.files("data", full.names = TRUE)) %>% 
  setNames("file_name") %>% 
  mutate(data = map(file_name, importing_data)) %>% 
  unnest(data) %>% 
  mutate(year = readr::parse_number(file_name),
         city = coalesce(city, residence),
         display_name = str_replace_all(display_name, "[^a-zA-Z0-9]", " ")) %>% 
  filter(!is.na(display_name)) %>% 
  select(-file_name, -residence)
  
  
boston_df %>% 
  mutate()
  
  mutate(first_name = 
    last_name = str_split(display_name, " "))
separate(display_name, c("first_name", "last_name"), sep = " ")
gsub("^(.*?)\\s.*", "\\1", names)

  

  

```


